# Generated by Django 3.0.dev20190607104439 on 2019-07-01 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sexo', models.TextField(choices=[['Feminino', 'Feminino'], ['Masculino', 'Masculino'], ['Trans', 'Trans'], ['Gay', 'Gay'], ['Bi', 'Bi'], ['Nao binario', 'Nao binario'], ['Outro', 'Outro']], max_length=50)),
                ('data', models.DateField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('imc', models.FloatField()),
                ('avaliacao', models.CharField(choices=[['Menor que 18,5 - Abaixo do peso', 'Menor que 18,5 - Abaixo do peso'], ['Entre 18,5 e 24,9 - Peso Normal', 'Entre 18,5 e 24,9 - Peso Normal'], ['Entre 25 e 29,9 - Sobrepeso', 'Entre 25 e 29,9 - Sobrepeso'], ['Entre 30 e 34,9 - Obesidade grau 1', 'Entre 30 e 34,9 - Obesidade grau 1'], ['Entre 35 e 39,9 - Obesidade grau 2', 'Entre 35 e 39,9 - Obesidade grau 2'], ['Mais do que 40 - Obesidade grau 3', 'Mais do que 40 - Obesidade grau 3']], max_length=30)),
                ('endereco', models.CharField(max_length=50)),
                ('plano', models.TextField(choices=[['1 modalidade - Bronze  R$60,00', '1 modalidade - Bronze  R$60,00'], ['2 modalidades - Prata R$100,00', '2 modalidades - Prata R$100,00'], ['3 modalidades - Ouro R$120,00', '3 modalidades - Ouro R$120,00'], ['Academia liberada - Diamante R$ de um rim', 'Academia liberada - Diamante R$ de um rim']], max_length=30)),
                ('meta', models.TextField(choices=[['Eliminar peso', 'Eliminar peso'], ['Ganhar massa', 'Ganhar massa'], ['Saude', 'Saude'], ['Outro', 'Outro']], max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
