# Generated by Django 2.2.3 on 2019-07-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='avaliacao',
            field=models.CharField(choices=[['Menor que 18,5 - Abaixo do peso', 'Menor que 18,5 - Abaixo do peso'], ['Entre 18,5 e 24,9 - Peso Normal', 'Entre 18,5 e 24,9 - Peso Normal'], ['Entre 25 e 29,9 - Sobrepeso', 'Entre 25 e 29,9 - Sobrepeso'], ['Entre 30 e 34,9 - Obesidade grau 1', 'Entre 30 e 34,9 - Obesidade grau 1'], ['Entre 35 e 39,9 - Obesidade grau 2', 'Entre 35 e 39,9 - Obesidade grau 2'], ['Mais do que 40 - Obesidade grau 3', 'Mais do que 40 - Obesidade grau 3']], max_length=50),
        ),
    ]
